{
 "title": "Confluent Cloud MT",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "CountryPrefix",
    "label": "Country",
    "query": {
     "query": "label_values(confluent_kafka_topic_partitions_count, country)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Country Topic Distribution",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(country) (confluent_kafka_topic_partitions_count)",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Topic Partition Chart (by Country)",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 2, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(country) (confluent_kafka_topic_partitions_count)"
    }
   ]
  },
  {
   "title": "Country Topic Chart",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 4, "x": 7, "y": 1 },
   "targets": [
    {
     "expr": "sum by(country) (confluent_kafka_topic_partitions_count)",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Cluster Topic Partition Distribution",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 5, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(kafka_id) (confluent_kafka_topic_partitions_count)",
     "legendFormat": "{{kafka_id}}"
    }
   ]
  },
  {
   "title": "Cluster Topic Partition Chart",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 5, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum by(kafka_id) (confluent_kafka_topic_partitions_count)",
     "legendFormat": "{{kafka_id}}"
    }
   ]
  },
  { "title": "Domain Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Topic Partition Count (by Domain)",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(businessDomain) (confluent_kafka_topic_partitions_count{country=~\"$CountryPrefix\", businessDomain!=\"None\"})",
     "legendFormat": "{{businessDomain}}"
    }
   ]
  },
  {
   "title": "Topic Partition Count (by Domain)",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 2, "x": 6, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(businessDomain) (confluent_kafka_topic_partitions_count{country=~\"$CountryPrefix\", businessDomain!=\"None\"})",
     "legendFormat": "{{kafka_id}}"
    }
   ]
  },
  {
   "title": "Topic Partition Count (by Domain)",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 5, "x": 8, "y": 14 },
   "targets": [
    {
     "expr": "sum by(businessDomain) (confluent_kafka_topic_partitions_count{country=~\"$CountryPrefix\", businessDomain!=\"None\"})",
     "legendFormat": "{{businessDomain}}"
    }
   ]
  },
  {
   "title": "Topic Partition Count (By Country Domain)",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 8, "x": 13, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(country, businessDomain) (confluent_kafka_topic_partitions_count{country=~\"$CountryPrefix\", businessDomain!=\"None\"})",
     "legendFormat": "{{country}}-{{businessDomain}}"
    }
   ]
  },
  {
   "title": "ksqlDB Internal Topics",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(ksqlDBCluster) (confluent_kafka_topic_partitions_count{country=~\"$CountryPrefix\", ksqlDBCluster!=\"n/a\"})",
     "legendFormat": "{{ksqlDBCluster}}"
    }
   ]
  },
  {
   "title": "ksqlDB Internal Topics",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 6, "x": 6, "y": 29 },
   "targets": [
    {
     "expr": "sum by(ksqlDBCluster) (confluent_kafka_topic_partitions_count{country=~\"$CountryPrefix\", ksqlDBCluster!=\"n/a\"})",
     "legendFormat": "{{ksqlDBCluster}}"
    }
   ]
  },
  { "title": "Environment Partition Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 } },
  {
   "title": "Environment overview",
   "type": "piechart",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(env) (confluent_kafka_topic_partitions_count{country=~\"$CountryPrefix\"})",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Environment overview",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 6, "x": 6, "y": 45 },
   "targets": [
    {
     "expr": "sum by(env) (confluent_kafka_topic_partitions_count{country=~\"$CountryPrefix\"})",
     "legendFormat": "{{env}}"
    }
   ]
  },
  {
   "title": "Detail Cluster Environment Topic Partition Distribution",
   "type": "bargauge",
   "gridPos": { "h": 15, "w": 9, "x": 12, "y": 45 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(env, kafka_id) (confluent_kafka_topic_partitions_count{country=~\"$CountryPrefix\"})",
     "legendFormat": "{{env}} in {{kafka_id}}"
    }
   ]
  }
 ]
}